development:
  adapter: postgresql
  encoding: unicode
  database: bookmarks_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: bookmarks_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: bookmarks_production
  pool: 5
  username: bookmarks
  password:
